# Build and run: docker compose up --build

version: "3.9"

services:
  backend:
    build: .
    container_name: ragdocs-backend
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - LLM_API_KEY=${LLM_API_KEY}
    restart: unless-stopped
    # mem_limit: '1g'
    # cpus: 0.5

  ollama:
    image: ollama/ollama
    platform: linux/arm64
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    restart: unless-stopped
    # mem_limit: '8g'
    # cpus: 6

volumes:
  ollama_models:
